---
development:
  cloud_name: amreos
  api_key: '723417722633884'
  api_secret: T2MDmC1_7hapoNAjo0txyCqevcQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: amreos
  api_key: '723417722633884'
  api_secret: T2MDmC1_7hapoNAjo0txyCqevcQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: amreos
  api_key: '723417722633884'
  api_secret: T2MDmC1_7hapoNAjo0txyCqevcQ
  enhance_image_tag: true
  static_image_support: false
